# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build reference file'
        # Default value if no value is explicitly provided
        default: 'zig_out'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    name: Build and Install 
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build install

